language: node_js
node_js: "13"

services:
  - docker

before_install:
  - sudo apt-get -y update || true
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-rc.23/lando-v3.0.0-rc.23.deb
  - sudo dpkg -i /tmp/lando-latest.deb
  - lando version

before_script:
  - lando start
  - npx wait-on --timeout 30000 http://wikibus-sources.lndo.site

jobs:
  include:
    - env:
        - JOB=analyser
      script:
        - docker-compose -f docker-compose.yml -f docker-compose.posix.yml run analyser
    - env:
        - JOB=e2e
      script:
        - docker-compose -f docker-compose.yml -f docker-compose.posix.yml run e2e-tests

